theme: jekyll-theme-architect

title: 梶本修一
description: CeVIOを衝動買いしたので実況動画を作ってみたい
youtube-channel_url: https://www.youtube.com/channel/UCXEV4sSbUKp3RTwy7cIOV8g
niconico-channel_url: https://www.nicovideo.jp/user/117623175
